steps:
  # Step 1: Check out the repository
  - name: Checkout code
    uses: actions/checkout@v3

  # Step 2: List files for debugging
  - name: List files
    run: ls -R

  # Step 3: Set up Python
  - name: Set up Python
    uses: actions/setup-python@v4
    with:
      python-version: '3.11'

  # Step 4: Install dependencies
  - name: Install dependencies
    run: |
      python -m pip install --upgrade pip
      pip install requests pygithub

  # Step 5: Run the code review script
  - name: Run code review bot
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      OPENROUTER_API_KEY: ${{ secrets.OPENROUTER_API_KEY }}
    run: |
      python scripts/code_review_bot.py
